let quotes = [
    `The only way to do great work is to love what you do.`,
    `Believe you can and you're halfway there.`,
    `The future belongs to those who believe in the beauty of their dreams.`,
    `Strive not to be a success, but rather to be of value.`,
    `The mind is everything. What you think you become.`,
    `Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.`,
    `I have not failed. I've just found 10,000 ways that won't work.`,
    `It is during our darkest moments that we must focus to see the light.`,
    `The best revenge is massive success.`,
    `You miss 100% of the shots you don't take.`,
    `The only true wisdom is in knowing you know nothing.`,
    `To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.`,
    `Life is what happens when you're busy making other plans.`,
    `Get busy living or get busy dying.`,
    `The greatest glory in living lies not in never falling, but in rising every time we fall.`,
    `It's not whether you get knocked down, it's whether you get up.`,
    `Innovation distinguishes between a leader and a follower.`,
    `The expert in anything was once a beginner.`,
    `The only person you are destined to become is the person you decide to be.`,
    `If you want to live a happy life, tie it to a goal, not to people or things.`,
    `Never go to bed mad. Stay up and fight.`,
    `You only live once, but if you do it right, once is enough.`,
    `Many of life's failures are people who did not realize how close they were to success when they gave up.`,
    `Success is not final, failure is not fatal: it is the courage to continue that counts.`,
    `The way to get started is to quit talking and begin doing.`,
    `The best way to predict the future is to create it.`,
    `Imagination is more important than knowledge.`,
    `Do what you can, with what you have, where you are.`,
    `What we achieve inwardly will change outer reality.`,
    `Keep your eyes on the stars, and your feet on the ground.`,
    `The most difficult thing is the decision to act, the rest is merely tenacity.`,
    `Build your own dreams, or someone else will hire you to build theirs.`,
    `The journey of a thousand miles begins with a single step.`,
    `That which does not kill us makes us stronger.`,
    `I alone cannot change the world, but I can cast a stone across the waters to create many ripples.`,
    `Whether you think you can or you think you can't, you're right.`,
    `The mind, once stretched by a new idea, never returns to its original dimensions.`,
    `A truly rich man is one whose children run into his arms when his hands are empty.`,
    `It is never too late to be what you might have been.`,
    `An unexamined life is not worth living.`,
    `Everything you’ve ever wanted is on the other side of fear.`,
    `Challenges are what make life interesting and overcoming them is what makes life meaningful.`,
    `The only true wisdom is in knowing you know nothing.`,
    `If you are not willing to risk the usual, you will have to settle for the ordinary.`,
    `Patience is not the ability to wait, but the ability to keep a good attitude while waiting.`,
    `The only person you should try to be better than is the person you were yesterday.`,
    `Life is 10% what happens to you and 90% how you react to it.`,
    `Your time is limited, so don't waste it living someone else's life.`,
    `The power of imagination makes us infinite.`,
    `What we think, we become.`,
    `Don't count the days, make the days count.`,
    `The best way to find yourself is to lose yourself in the service of others.`,
    `If you light a lamp for someone else, it will also brighten your own path.`,
    `The only way to do great work is to love what you do.`,
    `Happiness is not something ready made. It comes from your own actions.`,
    `You are never too old to set another goal or to dream a new dream.`,
    `The function of leadership is to produce more leaders, not more followers.`,
    `Fall seven times, stand up eight.`,
    `It's not what you look at that matters, it's what you see.`,
    `To live is the rarest thing in the world. Most people exist, that is all.`,
    `The most effective way to do it, is to do it.`,
    `We are what we repeatedly do. Excellence, then, is not an act, but a habit.`,
    `Start where you are. Use what you have. Do what you can.`,
    `If you want to lift yourself up, lift up someone else.`,
    `Don't let yesterday take up too much of today.`,
    `The question isn't who is going to let me; it's who is going to stop me.`,
    `What lies behind us and what lies before us are tiny matters compared to what lies within us.`,
    `We can't help everyone, but everyone can help someone.`,
    `The only true wisdom is in knowing you know nothing.`,
    `Change your thoughts and you change your world.`,
    `Success is stumbling from failure to failure with no loss of enthusiasm.`,
    `Live as if you were to die tomorrow. Learn as if you were to live forever.`,
    `The less I needed, the happier I became.`,
    `It always seems impossible until it's done.`,
    `I have no special talent. I am only passionately curious.`,
    `The best way to cheer yourself up is to try to cheer somebody else up.`,
    `If you want to achieve greatness stop asking for permission.`,
    `When you cease to dream, you cease to live.`,
    `Opportunities don't happen, you create them.`,
    `The secret of getting ahead is getting started.`,
    `If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you.`,
    `Happiness is not the absence of problems, it's the ability to deal with them.`,
    `The only person you are destined to become is the person you decide to be.`,
    `Perfection is not attainable, but if we chase perfection we can catch excellence.`,
    `Whatever you are, be a good one.`,
    `You must be the change you wish to see in the world.`,
    `Set your goals high, and don't stop till you get there.`,
    `In order to write about life first you must live it.`,
    `The journey of a thousand miles begins with a single step.`,
    `The most courageous act is still to think for yourself. Aloud.`,
    `Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.`,
    `Life is a succession of lessons which must be lived to be understood.`,
    `The price of anything is the amount of life you exchange for it.`,
    `If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.`,
    `Success usually comes to those who are too busy to be looking for it.`,
    `Try to be a rainbow in someone's cloud.`,
    `It's hard to beat a person who never gives up.`,
    `We are what we repeatedly do. Excellence, then, is not an act, but a habit.`,
    `The mind is everything. What you think you become.`,
    `The future belongs to those who believe in the beauty of their dreams.`,
];

let authors = [
    `Steve Jobs`,
    `Theodore Roosevelt`,
    `Eleanor Roosevelt`,
    `Albert Einstein`,
    `Buddha`,
    `Robert Frost`,
    `Thomas A. Edison`,
    `Aristotle Onassis`,
    `Frank Sinatra`,
    `Wayne Gretzky`,
    `Socrates`,
    `Ralph Waldo Emerson`,
    `John Lennon`,
    `Stephen King`,
    `Nelson Mandela`,
    `Vince Lombardi`,
    `Steve Jobs`,
    `Helen Hayes`,
    `Ralph Waldo Emerson`,
    `Albert Einstein`,
    `Phyllis Diller`,
    `Mae West`,
    `Thomas A. Edison`,
    `Winston Churchill`,
    `Walt Disney`,
    `Peter Drucker`,
    `Albert Einstein`,
    `Theodore Roosevelt`,
    `Plutarch`,
    `Theodore Roosevelt`,
    `Amelia Earhart`,
    `Farrah Gray`,
    `Lao Tzu`,
    `Friedrich Nietzsche`,
    `Mother Teresa`,
    `Henry Ford`,
    `Oliver Wendell Holmes Sr.`,
    `Unknown`,
    `George Eliot`,
    `Socrates`,
    `George Addair`,
    `Joshua J. Marine`,
    `Socrates`,
    `Jim Rohn`,
    `Joyce Meyer`,
    `Unknown`,
    `Charles R. Swindoll`,
    `Steve Jobs`,
    `John Muir`,
    `Buddha`,
    `Muhammad Ali`,
    `Mahatma Gandhi`,
    `Buddha`,
    `Steve Jobs`,
    `Dalai Lama XIV`,
    `C.S. Lewis`,
    `Ralph Nader`,
    `Japanese Proverb`,
    `Henry David Thoreau`,
    `Oscar Wilde`,
    `Amelia Earhart`,
    `Aristotle`,
    `Arthur Ashe`,
    `Booker T. Washington`,
    `Will Rogers`,
    `Ayn Rand`,
    `Ralph Waldo Emerson`,
    `Ronald Reagan`,
    `Socrates`,
    `Norman Vincent Peale`,
    `Winston S. Churchill`,
    `Mahatma Gandhi`,
    `Charles Bukowski`,
    `Nelson Mandela`,
    `Albert Einstein`,
    `Mark Twain`,
    `Unknown`,
    `Malcolm Forbes`,
    `Chris Grosser`,
    `Mark Twain`,
    `Zig Ziglar`,
    `Steve Maraboli`,
    `Ralph Waldo Emerson`,
    `Vince Lombardi`,
    `Abraham Lincoln`,
    `Mahatma Gandhi`,
    `Bo Jackson`,
    `Ernest Hemingway`,
    `Lao Tzu`,
    `Coco Chanel`,
    `Martin Luther King Jr.`,
    `Ralph Waldo Emerson`,
    `Henry David Thoreau`,
    `J.K. Rowling (from Harry Potter)`,
    `Henry David Thoreau`,
    `Maya Angelou`,
    `Babe Ruth`,
    `Aristotle`,
    `Buddha`,
    `Eleanor Roosevelt`,
];

const quote = document.getElementById('p');
const author = document.getElementById('h4');
const getQuote = document.getElementById('button');

getQuote.addEventListener('click', () => {
    let randomNumber = Math.floor(Math.random() * 100);

    quote.textContent = `${quotes[randomNumber]}`;
    author.textContent = `${authors[randomNumber]}`;

})
